trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  dbProject: 'BasicDatabase'

steps:
- task: VSBuild@1
  displayName: Build DB Project
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
  
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Azure subscription 1(c731920e-f389-4198-98b9-bb54ff8f6bde)'
    AuthenticationType: 'server'
    ServerName: 'sqlautomatedchanges.database.windows.net'
    DatabaseName: 'basicdatabase'
    SqlUsername: 'ranjit123'
    SqlPassword: '$(passwordVariable)'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '**\*.dacpac'
    IpDetectionMethod: 'AutoDetect'
     

